# Dockerfile-broker
#FROM eclipse-mosquitto:2.0

# Espone la porta standard MQTT
#EXPOSE 1883

# Il comando di default è già mosquitto
#CMD ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]

FROM eclipse-mosquitto:latest

COPY mosquitto.conf /mosquitto/config/mosquitto.conf

EXPOSE 1883

CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]